name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pylint docker
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with PyLint
      run: pylint app.py
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd "$(pwd)"
        export PYTHONPATH="$PWD:$PYTHONPATH"
        pytest tests
    - name: Debug Docker Username # REMOVE THIS STEP AFTER DEBUGGING
      run: echo "Docker Hub Username: ${{ secrets.DOCKER_USERNAME }}"
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mars-mission-control:latest .
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mars-mission-control:latest